/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:5fcde78b-2ef2-4214-8436-a3273f7eaffd",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_Gzxwn80eo",
    "aws_user_pools_web_client_id": "1gic71kn61nhaohh04t9a56stm",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "photo-website-photos",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
