/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:9d5f68ed-c687-452a-83d9-95f5069d041a",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_dyyQuGZSJ",
    "aws_user_pools_web_client_id": "1a2pdpiorgf3tvo7dh09ol4qk",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "photo-website-photos",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
